language: node_js
node_js:
  - '14'
services:
  - mysql
cache: yarn
branches:
  only:
    - master
env:
  global:
    - PORT=3000
    - JWT_SECRET=thisisasamplesecret
    - JWT_ACCESS_EXPIRATION_MINUTES=30
    - JWT_REFRESH_EXPIRATION_DAYS=30
script:
  - yarn lint
  - yarn test
after_success: yarn coverage:coveralls
