version: '2.1'

services:
  db:
    container_name: db-node-app
    image: "postgres:latest"
    environment:
      - "POSTGRES_DB=${POSTGRES_DB}"
      - "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}"
      - "POSTGRES_USER=${POSTGRES_USER}"
    ports:
      - "${POSTGRES_PORT}:5432"
    networks:
      - node-network

  node-app:
    build: .
    image: node-app
    restart: always
    env_file:
      - .env
    ports:
      - '3000:3000'
    depends_on:
      - db
    volumes:
      - ./src:/usr/src/node-app/src
    networks:
      - node-network

networks:
  node-network:
    driver: bridge
